### ISSUE TITLE
カタカナの表記ゆれ

### ISSUE THREAD

**Issue by msmhrt** [g200kg/web-audio-api-ja#1]
簡単な表記ゆれチェッカーに試しにかけてみたところ、以下の結果になりましたので報告まで。
ほとんどは長音と中黒ですね。

イベントハンドラー(4)、イベントハンドラ(2)
インターフェース(92)、インータフェース(1)、インターフェイス(1)、インタフェース(1)
オーディオアプリケーション(3)、オーディオ・アプリケーション(1)
クワド(1)、クワッド(1)
ゲイン・コントロール(2)、ゲインコントロール(2)
コンサートホール(3)、コンサート・ホール(1)
コンピューティング・リソース(1)、コンピューティングリソース(1)
コンボリューション・エフェクト(3)、コンボリューションエフェクト(1)
パンニング・アルゴリズム(2)、パンニングアルゴリズム(2)
パンニング・モデル(1)、パンニングモデル(1)
フィルター(22)、フィルタ(3)
ボイス・ドロッピング(1)、ボイスドロッピング(1)
ボイス・ドロッピング・アルゴリズム(1)、ボイス・ドロッピングアルゴリズム(1)
ミュージック・ビジュアライザー(2)、ミュージックビジュアライザー(1)
モジュラー・ルーティング(3)、モジュラールーティング(1)

ついでですが、インタラクティプ、トスリーム、ディケイはTYPOだと思いますのでご確認ください。

**Comment by g200kg** [comment]
助かります。修正しました。
ひとつだけ、ディケイはDecay で、シンセ関係では良く使われる用語になっています。

ありがとうございました
