### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by mohayonao** [g200kg/web-audio-api-ja#2]
リンクが切れています
- convolution.html
  - https://github.com/g200kg/web-audio-api-ja/blob/gh-pages/index.html#L4317
- changelog.html
  - https://github.com/g200kg/web-audio-api-ja/blob/gh-pages/index.html#L4757

**Comment by g200kg** [comment]
ありがとうございます。取りあえず原文のままですが足りないファイルを追加しました。
changelogはともかく、convolutionの方はその内暇をみて追加で翻訳したいと思います。

**Comment by g200kg** [comment]
convolutionの実装ガイドを翻訳しました。
[http://g200kg.github.io/web-audio-api-ja/convolution.html](http://g200kg.github.io/web-audio-api-ja/convolution.html)

changelogの方は英語のままで良いかと思っています。
