### ISSUE TITLE
DynamicsCompressorNode の knee のデフォルト値が間違っています

### ISSUE THREAD

**Issue by mohayonao** [g200kg/web-audio-api-ja#3]
DynamicsCompressorNode の knee のデフォルト値が間違っています
- 誤: 20
- 正: 30

https://github.com/g200kg/web-audio-api-ja/blob/gh-pages/index.html#L2883

> このデフォルトの<code>value</code>は0から40の範囲中、**20** になっています。

https://github.com/WebAudio/web-audio-api/blob/gh-pages/index.html#L3251

> Its default <code>value</code> is **30**, with a nominal range of 0 to 40.

**Comment by g200kg** [comment]
ありがとうございます。修正しました。
