### ISSUE TITLE
「機能」セクションのコメント

### ISSUE THREAD

**Issue by momdo** [g200kg/web-audio-api-ja#4]
https://g200kg.github.io/web-audio-api-ja/#Features
>audio または video メディア要素からのオーディオに対する処理

メディア要素と訳されていますが、この箇所は`<code>`でマークアップされているので、訳出するとおかしなことになると思います。
もっと言うと、原文の`media element`がそもそも誤りで、おそらく`MediaElement`が正しいのではないでしょうか。

**Comment by g200kg** [comment]
ありがとうございます。元は多分 &lt;code> が必要ない所をマークアップしてしまったのかなという気がします。取り合えず英語のままにしておきます。
