### ISSUE TITLE
半角スペースの揺れ

### ISSUE THREAD

**Issue by momdo** [g200kg/web-audio-api-ja#6]
たとえば、
https://g200kg.github.io/web-audio-api-ja/#dom-baseaudiocontext-createconstantsource
> ConstantSourceNode･の･ファクトリーメソッド･です。

https://g200kg.github.io/web-audio-api-ja/#dom-baseaudiocontext-createconvolver
> ConvolverNode･の･ファクトリーメソッドです。

となっていて（わかりやすさのために、ここでは"･"を半角スペースの代わりに印付けしています）、半角スペースの規則が一定になっていないのが気になりました。

リンクの前後に半角スペースがあるので[Mozillaのガイドライン](https://github.com/mozilla-japan/translation/wiki/Editorial-Guideline)が近い気もしますが、半角英数字の前後にスペースがあるわけでもないので、これに従っているというわけでもなさそうですね。

いずれにしても、何らかの規則に従った表記にしていただけると、読みやすさが向上すると思いました。（[JTF日本語標準スタイルガイド](https://www.jtf.jp/jp/style_guide/styleguide_top.html)のように（英語以外では）一切スペースを入れない方法もあります。）

**Comment by g200kg** [comment]
ありがとうございます。現状は結構適当になってしまっています。少し時間がかかりそうですが、気持ち的には Mozilla のガイドラインに寄せて行きたいと思います。
